Algoritmo "Exercicio_21"
// Jeanne Torres da Silva
Var

 n1, n2, divi : inteiro

Inicio
escreva ("Digite um numero: ")
leia (n1)
escreva ("Digite outro numero: ")
leia (n2)
se n1 > n2 entao
     divi <- n1 div n2
senao
     divi <- n2  div n1
fimse
escreva (" o resultado da divisão inteira é ",divi)

Fimalgoritmo
//  Faça um programa que leia Leia dois números inteiros e exiba o
//resultado da divisão inteira do maior pelo menor.

