Algoritmo "Exercicio_27"

// Jeanne Torres da Silva
Var
 n1,n2 : inteiro


Inicio
 escreva ("Escreva um numero: ")
 leia (n1)
 escreva ("Digite outro numero: ")
 leia (n2)
 se n1=n2 entao
 escreva ("O  valor de ",n1," e ", n2, " sao iguais")
 senao
 escreva ("O  valor de ",n1," e ", n2, " nao sao iguais")
 
fimse

Fimalgoritmo
//Escreva um algoritmo que receba dois números inteiros e determine se eles são
// iguais ou diferentes.