Algoritmo "Exercicio_35"
// Jeanne Torres da Silva
Var
letra : caracter


Inicio
escreva ("Digite uma letra: ")
leia (letra)

se (letra = "a") ou (letra = "e") ou (letra = "i") ou (letra = "o") ou (letra = "u") ou (letra = "y") entao
escreva ("A letra (",letra, ") é uma vogal")
senao
escreva ("A letra (",letra, ") é uma consoante")
fimse



Fimalgoritmo
//Crie um programa que verifique se uma letra é uma vogal.