Algoritmo "Exercicio_23"
// Jeanne Torres da Silva
Var
 n1, modi : inteiro

Inicio
 escreva ("Digite um numero: ")
 leia (n1)
   modi <- n1 mod 2

escreval ("O resto da sua divisao é: ",modi)
escreva ("Se o resultado final for 0 entao ele é par, se for igual a 1 ele é impar")

Fimalgoritmo
//Faça um programa que leia um número inteiro e verifique se ele é par.
//Exiba o resto da divisão do número por 2.