Algoritmo "Exercicio_32"
//Jeanne Torres da Silva

Var
n1: inteiro

Inicio
escreva ("Digite um numero: ")
leia (n1)

 se n1 mod 5 = 0 entao
  escreva ("Divisivel por 5 resto ", n1 mod 5)
  senao
  escreva ("Nao divisivel por 5 sobrou ", n1 mod 5)
  fimse



Fimalgoritmo
//Faça um programa que leia um número inteiro e determine se ele é divisível
// por 5 utilizando o operador de resto. Mostre "Divisível por 5" ou
// "Não divisível por 5"
