Algoritmo "Exercicio_30"
// Jeanne Torres da Silva
Var
n1, idade : inteiro

Inicio
escreva ("Digite o ano que voce nasceu: ")
leia (n1)
idade <- (2024-n1)
se idade >= 16 entao
escreva ("Voce ja pode votar")
senao
escreva ("Voce ainda nao pode votar")
fimse



Fimalgoritmo


 //Faça um programa que leia o ano de nascimento de uma pessoa,
 //calcule a idade                                                0
 //dela e depois mostre se ela pode ou não votar.