Algoritmo "exercicio_72"
// Jeanne torres da silva
Var
   n1,contador, tabuada: inteiro



Inicio
   escreva ("Digite um numero: ")
   leia (n1)
   contador <-1
   para contador de contador ate 10 faca
      escreval ("a tabuada é :", n1 ," x ", contador, " = ",n1*contador)

   fimpara







Fimalgoritmo
//Crie um programa usando o "PARA" que mostre a tabuada
// digitada pelo usuário.
